In [ ]:
#--------------------------------01_Numpy1--------------------------------------------

import numpy as np # 넘파이 임포트

print(np.__version__) # 넘파이 버전 출력

arrA = [ 1, 2, 3, 4, 5 ] # 리스트
print(arrA, type(arrA))

matrixA = np.array(arrA) # 넘파이 배열 (ndarray : N-dimensional array)
print(matrixA, type(matrixA)) # [1 2 3 4 5] < class 'numpy.ndarray' >
matrixB = np.array([0.45, 5.5, 0, 3])
print(matrixB, type(matrixB)) # [ 0.45 5.5 0. 3.] < lass 'numpy.ndarray' >
matrixC = np.array(['a', 'b', 'c'])
print(matrixC, type(matrixC)) # ['a' 'b' 'c'] < class 'numpy.ndarray' >
matrixD = np.array([1, 2, 3, 'banana', 'cat'])
print(matrixD, type(matrixD)) # ['1' '2' '3' 'banana' 'cat'] < class 'numpy.ndarray' >

arr1d = np.array([1, 4, 5, 10 ])
print(arr1d)
print(arr1d.shape) # (4, )
arr2d = np.array([[1, 4, 5, 10 ], [10, 30, 50, 60]])
print(arr2d.shape) # (2, 4)
print(arr2d.ndim) # 2
print(arr2d.size) # 8
arr3d = np.array([[[1, 4, 5, 10 ], [10, 30, 50, 60], [10, 30, 50, 60]],[[1, 4, 5, 10 ], [10, 30, 50, 60], [10, 30, 50, 60]]])
print(arr3d.shape) # (2, 3, 4)
print(arr3d.ndim) # 3
print(arr3d.size) # 24

arr1 = np.zeros(10) # double 초기화
print(arr1) # [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. ]
arr2 = np.zeros([2,2])
print(arr2) # [0. 0.] [0. 0.]
arr3 = np.ones(10) # double
print(arr3) # [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ]
arr4 = np.ones([2,2]) # double
print(arr4) # [1. 1.] [1. 1.]
arr5 = np.empty([2,2]) # unknown values
print(arr5)
arr6 = np.empty(30)
print(arr6)

range(10) # 0~ 9
range(1,11) # 1~ 10
range(0,11,2) # 0 2 4 6 8 10
for i in range(0, 11, 2):
    print(i)
    
print(np.arange(20)) # 0~ 19 array
print(np.arange(1,30,2)) # 1 3 5 7 9 11 13 15 17 18 20 22 24 26 28 30
np.arange(0,30,5) # 0 5 10 15 20 25 30
np.arange(1,11) # 1 2 3 4 5 6 7 8 9 10
print(np.arange(1,11).reshape(2,5)) # [1 2 3 4 5] [ 6 7 8 9 10]

myArray = np.array([10,20,40,90,100,20])
myArray # [10 20 40 90 100 20]
myArray.reshape(-1,2) # [10 20] [40 90] [100 20]
print(myArray.reshape(-1,3)) # [10 20 40] [90 100 20]

arr2d = np.array([[1,4,5,6],[56,23,45,67],[8,4,6,10]])
arr2d
print(arr2d.flatten()) # 1 4 5 6 56 23 45 67 8 4 6 10

arr1 = np.array([1,2,3,4,5])
print(type(arr1)) # class type : <class 'numpy.ndarray'>
print(arr1.dtype) # data type : int
print(type(1)) # <class 'int'>
arr2 = np.array([1.1, 2.4 , 3, 4, 5]) # 실수형 ndarray
print(arr2.dtype) # data type : float64 ( double size )


arr1 = np.array([1,2,3,4])
arr1
print(arr1.dtype) # int32
arr2 = arr1.astype(float) # ndarray 형변환 메서드 astype ( to double size )
print(arr2, arr2.dtype) # int32 => float64 ( double size )

arr1 = np.arange(20,26) # 20 21 22 23 24 25
arr2 = np.arange(10,16) # 10 11 12 13 14 15
print(arr1, arr2)
print(arr1 + arr2) # 30 32 34 36 38 40 (행열의 덧셈)
arr1 - arr2
arr1 * arr2
print(arr1 / arr2) # 자동 형변환
animals = np.array([100, 200, 400, 6, 90])
animals
animals[0] # 100
animals[-1] # 90
print(animals[0:2]) # 100 200 ( 0~ 1)
myArray = np.arange(1,31) # 1~30 ndarray
myArray
myArray2 = myArray.reshape(5,6) # [1~6] [7~...] ...
print(myArray2)
myArray2[0,5] # 6
myArray2[0][5] # 6
myArray2[:, 0] # [1 7 13 19 25]
myArray2[0,:] # [1 2 3 4 5 6 7]
myArray2[:,:] # total
myArray2[0:2,:] # [1~6][7~12]
myArray2[:,1:4] # [2 3 4][8 9 10]... [26 27 28]
myArray2[2:6,3:6] # [16 17 18][22 23 24][28 29 30] # => 2:6 :: 2~5
arr1 = np.arange(1,11)
arr1
arr1[::2] # 2 interval => 1 3 5 7 9
arr1[1::2] # except 0 ++2 => 2 4 6 8 10
arr1[0:5:2] # 0~4 ++2 :: 0 2 4 => 1 3 5
arr2 = np.arange(1,21).reshape(-1,5) # 1~20
print(arr2)
arr2[::2,:]
arr2[:,::2]

### 퀴즈
1~15로 구성된 넘파이 배열을 3행5열로 구성하고 1,3,5열만 출력하여라

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])
       

In [3]:
quizarr = np.arange(1, 16).reshape(3, 5)
#print(quizarr)
quizarr = np.arange(1, 16).reshape(3, 5)[:,::2]
#print(quizarr)
quizarr = np.arange(1, 16).reshape(3, 5)[::2, ::3]
print(quizarr)

[[ 1  4]
 [11 14]]


In [ ]:
#--------------------------------01_Numpy2--------------------------------------------

import random

random.random() # 0~1 사이 실수형 난수
random.randint(1,6) # 1~5사이 정수
random.randrange(1, 101, 2) # 1~101 사이의 홀수(1에서 ++2한 값들 중)
random.randrange(2, 101, 2) # 2~101 사이의 짝수(2에서 ++2한 값들 중)

random.random() # 0~1 사이 실수형 난수
random.uniform(10, 20) # n~m 사이 실수형 난수

random.choice(range(2, 101, 2))# == random.randrange(2,101,2)
random.choice(['철수','영희','로미오','줄리엣','지니'])

numlist = [1,2,3,4,5,6,7,8,9]
random.sample(numlist, 3) # numlist에서 3개

frutes = ('사과', '귤', '포도', '배')
random.sample(frutes, 2) # 튜플에서 샘플링도 가능

import numpy as np

#0~ 1사이의 실수 5개, 2,3의 배열
np.random.rand(5)
np.random.rand(2,3)

#
np.random.randn(5)
np.random.randn(2,3)

#
np.random.randint(-10,11,size=5)
np.random.randint(10, 20, size=(3, 5))

#시드 설정
#np.random.seed(10)
np.random.rand(10)

# 0~10 중에서 4개 중복허용
np.random.choice(11, size=4, replace=True)
np.random.choice(['사자','코끼리','펭귄',
                  '물소','기린','얼룩말','토끼'],
                 size=3, replace=False) #중복 x

np.random.seed(2)
np.random.choice(np.arange(1, 47), 3, replace=False)

#섞기
mylist = [3,4,5,2,1]
np.random.shuffle(mylist)
mylist

# 소숫점 표시
arr1 = np.array()

### 퀴즈<01>

In [45]:
arr1 = np.random.randn(10) # 표준분표 난수
arr2 = np.random.randn(10)

arr3 = np.maximum(arr1,arr2)
arr4 = np.minimum(arr1,arr2)
# print(arr1)
# print(arr2)
# print(arr3)
# print(arr4)

arrA = ([1,100,-10,45, 33, 50, 200])
arrB = np.array([[1, 2, 4, 7],
         [9, 88, 6, 45],
         [100, 6, 4, 88]])

np.argmax(arrA) # 최대값의 인덱스
np.argmin(arrA) # 최소값의 인덱스
np.argmax(arrB, axis=0) # 세로열에서 제일 큰 값

arr1 = np.arange(1,11)
arr1.sum() #합
arr1.mean() #평균
 
arrB.sum(axis=0) # 세로 컬럼의 합
arrB.mean(axis=1) # 가로 로우의 평균

a = np.array(([1,2,3],[4,5,6]))
b = np.array(([4,5,6],[7,8,9]))

# print(a, b)

# print(np.vstack((a,b))) # 행 합치기
# print(np.hstack((a,b))) # 열 합치기
# print(np.concatenate((a,b), axis=0)) # 행 합치기
# print(np.concatenate((a,b), axis=1)) # 열 합치기

a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

a.dot(b)

arr = np.random.randn(10) 
np.sort(arr) # 정방향 정렬
np.sort(arr)[::-1] # 역방향 정렬

arr2d = np.random.randn(3,4)
np.sort(arr2d, axis=0) # 행 방향으로 오름차순
np.sort(arr2d, axis=1) # 열 방향으로 오름차순

np.sort(arr2d,axis=0)[::-1] # 행 방향 및 내림차순

ints = np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints) # 중복 제거 => [3, 2, 1, 4]

np.identity(4, dtype=int) # 정사각형 배열, 대각선 1

np.eye(N=3, M=4, k=2) # (행, 열, 1시작 위치)

matrix = np.arange(9).reshape(3,3)
np.diag(matrix)
np.diag(matrix, k=1) # (리스트, 값 추출 위치)


array([1, 5])

### 퀴즈<01>
1~10까지의 ndarray 배열 생성후<br>
np.log10(), np.sqrt() 함수 적용하기<br>
소숫점 결과는 3번째 자리에서 반올림한다.<br>

In [5]:
np.set_printoptions(precision=2)
arr = np.arange(1,11)
print(np.log10(arr))
print(np.sqrt(arr))

[0.   0.3  0.48 0.6  0.7  0.78 0.85 0.9  0.95 1.  ]
[1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.   3.16]


### 퀴즈<02>
./data/movielens-1m/ratings.dat 파일을 읽고 데이터 분석하기


- 전체 평균 평점 계산하기
- 각 사용자 별 평균 평점 계산하기
- ./myfile/mean_rating_by_user.csv 파일에 저장하기

In [51]:
import numpy as np
data = np.loadtxt("data/movielens-1m/ratings.dat", delimiter='::', dtype=np.int64)
# 데이터 받아오기

In [59]:
# 전체 평균 평점
round(data[:,2].mean(),2)

3.58

In [64]:
# 각 사용자 별 레이팅
user_ids = np.unique(data[:, 0]) # 첫번째 열의 distinct

user_rate = []
for userid in user_ids:
    user_rate.append((userid, data[data[:,0] == userid][:,2]))

user_rate

[(1, array([5, 3, 3, 4, 5, 3, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 3, 4, 5, 4, 3, 3,
         5, 5, 3, 5, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4, 4,
         4, 5, 5, 4, 5, 4, 4, 4, 4], dtype=int64)),
 (2, array([5, 4, 4, 3, 4, 4, 5, 3, 3, 3, 5, 4, 3, 3, 2, 5, 3, 4, 3, 4, 2, 3,
         2, 3, 4, 3, 5, 3, 5, 4, 2, 4, 5, 5, 4, 5, 4, 4, 2, 3, 5, 3, 3, 4,
         5, 4, 3, 3, 3, 5, 4, 4, 4, 5, 4, 5, 3, 3, 4, 3, 3, 2, 5, 4, 5, 3,
         5, 5, 3, 3, 4, 4, 2, 5, 5, 3, 4, 4, 5, 3, 2, 3, 4, 3, 4, 3, 4, 3,
         3, 5, 4, 3, 5, 5, 4, 1, 3, 3, 2, 5, 5, 4, 4, 4, 5, 3, 4, 4, 3, 4,
         4, 3, 3, 3, 5, 5, 5, 4, 3, 5, 4, 2, 3, 3, 5, 2, 5, 1, 5],
        dtype=int64)),
 (3, array([4, 2, 3, 4, 3, 4, 4, 4, 3, 3, 5, 3, 5, 4, 5, 4, 5, 3, 2, 5, 4, 3,
         4, 1, 4, 4, 2, 5, 5, 4, 4, 5, 5, 5, 5, 3, 4, 5, 5, 3, 4, 4, 2, 4,
         5, 4, 4, 4, 4, 5, 4], dtype=int64)),
 (4, array([5, 3, 4, 4, 4, 5, 5, 4, 2, 5, 5, 4, 4, 4, 4, 5, 1, 5, 5, 5, 5],
        dtype=int64)),
 (5, array([4, 4, 5, 3, 2, 5,

In [70]:
# 레이팅 평균
user_rateAvgs = []
for (x, y) in user_rate:
    user_rateAvgs.append([x, round(y.mean(),2)])
    
user_rateAvgs

[[1, 4.19],
 [2, 3.71],
 [3, 3.9],
 [4, 4.19],
 [5, 3.15],
 [6, 3.9],
 [7, 4.32],
 [8, 3.88],
 [9, 3.74],
 [10, 4.11],
 [11, 3.28],
 [12, 3.83],
 [13, 3.39],
 [14, 3.32],
 [15, 3.32],
 [16, 3.03],
 [17, 4.08],
 [18, 3.65],
 [19, 3.57],
 [20, 4.08],
 [21, 2.91],
 [22, 3.07],
 [23, 3.32],
 [24, 3.95],
 [25, 3.74],
 [26, 2.96],
 [27, 4.17],
 [28, 3.76],
 [29, 3.58],
 [30, 3.49],
 [31, 3.73],
 [32, 3.62],
 [33, 3.5],
 [34, 3.87],
 [35, 3.54],
 [36, 4.2],
 [37, 3.7],
 [38, 3.58],
 [39, 3.56],
 [40, 3.45],
 [41, 3.48],
 [42, 3.74],
 [43, 4.12],
 [44, 3.63],
 [45, 2.95],
 [46, 4.22],
 [47, 3.91],
 [48, 3.07],
 [49, 3.71],
 [50, 3.07],
 [51, 3.82],
 [52, 3.56],
 [53, 4.24],
 [54, 4.03],
 [55, 4.12],
 [56, 3.97],
 [57, 2.91],
 [58, 3.97],
 [59, 3.47],
 [60, 3.41],
 [61, 2.78],
 [62, 3.57],
 [63, 3.43],
 [64, 4.15],
 [65, 4.35],
 [66, 3.85],
 [67, 4.3],
 [68, 3.75],
 [69, 4.15],
 [70, 3.7],
 [71, 3.76],
 [72, 3.7],
 [73, 3.36],
 [74, 4.05],
 [75, 4.01],
 [76, 4.17],
 [77, 2.95],
 [78, 3.66],
 [7

In [73]:
np.savetxt("myfile/mean_rating_by_user.csv", user_rateAvgs, fmt='%-10d %.3f', delimiter=',')
# 데이터 형식에 맞춰 저장